Decidable: translate proof-by-relfection
Agda-zh/PLFA-zh pull request #83
Opened 2020-10-25 09:10 UTC by oshmkufa2010

2020-10-28 04:50 UTC, OlingCat requested changes

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +让我们重新审视章节 [Naturals]({{ site.baseurl }}/Naturals/) 中 monus 的定义。
```suggestion
我们来回顾一下 [Naturals]({{ site.baseurl }}/Naturals/) 一章中 `monus` 的定义。
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +我们可以用其他方式定义吗？可以定义一版带有守卫的减法──只有 `n ≤ m` 时才能从 `m` 中减去 `n` ：
```suggestion
我们可以用其他方式定义吗？可以定义一版带有**守卫（guarded）**的减法──只有当 `n ≤ m` 时才能从 `m` 中减去 `n` ：
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +不幸的是，这种定义难以使用，因为我们必须显示地为`n ≤ m`提供证明：
```suggestion
然而这种定义难以使用，因为我们必须显示地为`n ≤ m`提供证明：
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +这个问题没有通用的解决方案，但是在上述的情景下，我们恰好静态地知道这两个数字。这种情况下，我们可以使用一种被称为 *反射证明* 的技术。
```suggestion
这个问题没有通用的解决方案，但是在上述的情景下，我们恰好**静态地**知道这两个数字。这种情况下，我们可以使用一种被称为**反射证明（Proof by Reflection）**的技术。
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +实质上，在类型检查的时候我们可以让 Agda 运行可判定的等式 `n ≤ m` 并且保证 `n ≤ m`！
```suggestion
实质上，在类型检查的时候我们可以让 Agda 运行可判定的等式 `n ≤? m` 并且保证 `n ≤ m`！
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +我们使用隐式的一个特性来实现这个功能。如果 Agda 可以填充一个记录类型的所有字段，那么 Agda 就可以填充此记录类型的隐式。
```suggestion
我们使用「隐式参数」这一特性来实现这个功能。如果 Agda 可以填充一个记录类型的所有字段，那么 Agda 就可以填充此记录类型的隐式参数。
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +由于空记录类型没有任何字段，Agda总是会设法填充空记录类型的隐式。这就是`⊤`类型被定义成空记录的原因。
```suggestion
由于空记录类型没有任何字段，Agda 总是会设法填充空记录类型的隐式参数。这就是`⊤`类型被定义成空记录的原因。
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +- 如果 `n ≤ m` 成立，隐式参数的类型规约为 `⊤`。 然后Agda会开心地提供隐式参数。
```suggestion
如果 `n ≤ m` 成立，隐式参数的类型会规约为 `⊤`。 然后 Agda 会欣然提供隐式参数。
```

2020-10-28 04:50 UTC, OlingCat commented on src/plfa/part1/Decidable.lagda.md
> +事实证明，这种惯用语法非常普遍。标准库为 `T ⌊ ? ⌋` 定义了叫做 `True` 的代名词：
```suggestion
事实上，这种惯用语法非常普遍。标准库为 `T ⌊ ? ⌋` 定义了叫做 `True` 的同义词：
```

2020-11-06 11:25 UTC, fangyi-zhou commented
Don't forget to add yourself to the translators in the metadata

2020-11-13 13:29 UTC, fangyi-zhou approved these changes

2020-11-13 13:29 UTC, fangyi-zhou commented on src/plfa/part1/Decidable.lagda.md
> +然而这种定义难以使用，因为我们必须显式地为`n ≤ m`提供证明：
```suggestion
然而这种定义难以使用，因为我们必须显式地为 `n ≤ m` 提供证明：
```

2020-11-13 13:29 UTC, fangyi-zhou commented on src/plfa/part1/Decidable.lagda.md
> +由于空记录类型没有任何字段，Agda 总是会设法填充空记录类型的隐式参数。这就是`⊤`类型被定义成空记录的原因。
```suggestion
由于空记录类型没有任何字段，Agda 总是会设法填充空记录类型的隐式参数。这就是 `⊤` 类型被定义成空记录的原因。
```

2020-11-16 09:08 UTC, merged