Bigstep: translated
Agda-zh/PLFA-zh pull request #90
Opened 2021-10-31 14:30 UTC by starxingchenc

2021-10-31 16:12 UTC, alissa-tung requested changes

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +传名调用求值策略是在 λ-演算中计算程序值的一种确定性方法。
可以稍候讨论下类似 deterministic method 词组的翻译

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +传名调用求值策略是在 λ-演算中计算程序值的一种确定性方法。
第一次出现专有名词的时候建议标注一下原文

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +但是由于这是 λ-演算中指称语义的一个简单性质，
这里 `λ-演算` 的位置可能可以调整一下

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +相对的小步规约关系被写做 `M —→ M′`，它仅完成一步子计算来将 `M` 规约为另一个表达式 `M′`。
我不要确定会不会改成 `相对地` 比较好，或者 `而…则…`
single 可以或许写成一次？这里的 step 太多了

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +为了表示变量和函数应用，我们要么像在 `—→` 中一样使用替换，要么使用一个**环境（environment）**。
handle 和 representation 感觉不太一样

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +传名调用中的环境是一个从变量到闭包（即项与环境的值对）的映射。
（其实我更倾向于 创建项的环境 或者 对应的环境 之类的说法）

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +<!--
在别的章节 substitution 翻译成了代换

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +* `⇓-lam` 规则通过将一个 λ-抽象与其环境包装，将其转变为一个闭包。
可以调整为通过包装…将其，可以减少一个

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +## 大步语义是确定性的
在别的章节写作确定的

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +也就是说，传名调用关系是一个 partial function。该证明是两个大步语义推论的简单归纳。
TODO

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +也就是说，传名调用关系是一个 partial function。该证明是两个大步语义推论的简单归纳。
或许可以写成 由归纳 一类的东西

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +## 大步求值蕴含 β-规约
to a lambda

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +该证明通过对大步语义归纳来完成。通常，我们需要推广命题以完成归纳。
derivation

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +    如果 γ ⊢ M ⇓ V  且  γ ≈ₑ σ,
这里是不是 quote code 一下比较好？有空的话看看要不要给原文 patch merge request

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +在开始证明之前，我们需要建立一些有关等价环境和替换的引理。
equivalent environments and substitutions

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +在文章**Call-by-name, call-by-value, and the λ-calculus**中，
可能需要加空格

2021-10-31 16:12 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +为了更好阐述该证明，我们推荐阅读由 Felleisen，Findler，和 Flatt 所著的
可能需要去掉多余逗号，在中文语境下顿号或许好一些？需要讨论下

2021-10-31 16:13 UTC, alissa-tung commented
lgtm, thx

2021-11-01 04:28 UTC, alissa-tung requested changes

2021-11-01 04:28 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +**Semantics Engineering with PLT Redex** 的第五章。
西文书名好像一般用 _text_

2021-11-01 05:04 UTC, starxingchenc commented on src/plfa/part2/BigStep.lagda.md
> +<!--
在 Lambda 章节翻成了替换，而在 DeBruijn 章节翻成了代换
可能需要讨论统一一下

2021-11-02 03:52 UTC, alissa-tung approved these changes

2021-11-02 03:54 UTC, alissa-tung requested changes

2021-11-02 03:54 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
>  The proof of the backward direction, that beta reduction to a lambda
beta reduction to a lambda

2021-11-02 03:55 UTC, alissa-tung requested changes

2021-11-02 03:55 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +反向的证明，也就是项的 β-规约蕴含大步语义求值是更困难的。
The proof of the backward direction, that beta reduction to a lambda

2021-11-02 04:00 UTC, alissa-tung commented on src/plfa/part2/BigStep.lagda.md
> +    如果 γ ⊢ M ⇓ V  且  γ ≈ₑ σ,
markdown 对嵌套关系处理的不太好，所以不用管这个也可以

2021-11-02 09:48 UTC, fangyi-zhou commented
Needs rebase after solving conflicts, otherwise LGTM. Revisions can be done in later rounds if minor

2021-11-02 22:06 UTC, merged

2021-11-02 22:07 UTC, fangyi-zhou commented
Merged manually