Fix a translation error
Agda-zh/PLFA-zh pull request #95
Opened 2022-03-23 04:01 UTC by KDr2

And incidentally, fixed an emacs settings error.

2022-03-23 05:43 UTC, alissa-tung commented
Should we merge this [change](https://github.com/plfa/plfa.github.io/commits/dev/dotdir-locals.el) btw?

2022-03-23 06:45 UTC, KDr2 commented
> Should we merge this [change](https://github.com/plfa/plfa.github.io/commits/dev/dotdir-locals.el) btw?

Oh, I didn't know that commit before you mentioned it, but https://github.com/plfa/plfa.github.io/issues/516 was the same issue I found when I was reading the book in my emacs. So after some debugging, I found the issue in `.dir-local.el` and managed to find a way to fix it.

I think https://github.com/plfa/plfa.github.io/commit/463361eb1313f2c48716556f47b15a5241ae5b42 is a workaround when one wasn't familiar with emacs, it will be better to port the change of that file to the original repo :slightly_smiling_face:

2022-03-23 07:31 UTC, starxingchenc requested changes

2022-03-23 07:31 UTC, starxingchenc commented on src/plfa/part1/Relations.lagda.md
> +我们将 `_≤_` 的优先级设置为 4，所以它不如优先级为 6 的 `_+_` 结合地紧，因而，
应为 “结合得紧”

2022-03-23 07:36 UTC, KDr2 commented on src/plfa/part1/Relations.lagda.md
> +我们将 `_≤_` 的优先级设置为 4，所以它不如优先级为 6 的 `_+_` 结合地紧，因而，
:+1: updated.

2022-03-23 07:50 UTC, starxingchenc approved these changes

2022-03-24 23:52 UTC, fangyi-zhou requested changes
Please remove the changes regarding emacs. It would be nice if you can upstream this change and we can pull this from upstream

2022-03-25 00:47 UTC, KDr2 commented
> Please remove the changes regarding emacs. It would be nice if you can upstream this change and we can pull this from upstream

OK, updated.

2022-03-25 12:47 UTC, merged